exports.create = {
    User: [
        { 
            'name.first': 'Inkvisitor',
            'name.last': 'Great',
            'email': 'admin@pushkin.vk',
            'password': 'admin', 
            'isAdmin': true,
            'authors': ['', ''],
            __ref: 'admin',
        }
    ],


    Author: [
        {
            'name.first': 'Абрамов',
            'name.last': 'Фёдор',
            'patronymic': 'Александрович',
            'birthDay': new Date(1920, 1, 29),
            'deathDay': new Date(1983, 4, 14),
            'birthCountry': 'СССР',
            'birthCity': 'село Веркола, Архангельская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%B1%D1%80%D0%B0%D0%BC%D0%BE%D0%B2,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'Государственная премия СССР (1975), Орден Ленина (1980), Медаль «За оборону Ленинграда», Орден Отечественной войны II степени, Медаль «За победу над Германией в Великой Отечественной войне 1941—1945 гг.»',
            'additionalLinks': 'http://fabramov.ru/, http://russia.tv/brand/show/brand_id/10549',
            'authorPhoto': {filename: 'abramovProfilePhoto.jpg'},
            // 'children': 'Вася, Маша',
            'parents': 'Степанида Павловна (крестьянка из староверов), Александр Степанович (извозчик)',
            __ref: 'fedorAbramov'
        },
        {
            'name.first': 'Ахматова',
            'name.last': 'Анна',
            'patronymic': 'Андреевна',
            'birthDay': new Date(1889, 5, 23),
            'deathDay': new Date(1966, 2, 5),
            'birthCountry': 'Украина',
            'birthCity': 'Одесса',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D1%85%D0%BC%D0%B0%D1%82%D0%BE%D0%B2%D0%B0,_%D0%90%D0%BD%D0%BD%D0%B0_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%BD%D0%B0',
            'honors': '	«Этна-Таормина» (1964, Италия), номинация на Нобелевскую премию по литературе (1965, 1966)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'achmatovaProfilePhoto.jpg'},
            'children': 'Лев Гумилёв',
            'parents': 'Андрей Антонович Горенко (потомственный дворянин, инженер-механик), Инна Эразмовна',
            __ref: 'annaAchmatova',
            'user': 'admin'
        },
        {
            'name.first': 'Бродский',
            'name.last': 'Иосиф',
            'patronymic': 'Александрович',
            'birthDay': new Date(1940, 4, 24),
            'deathDay': new Date(1996, 0, 28),
            'birthCountry': 'СССР',
            'birthCity': 'Ленинград',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D0%B9,_%D0%98%D0%BE%D1%81%D0%B8%D1%84_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'Нобелевская премия по литературе (1987), Стипендия Макартура (1981), Поэт-лауреат США (1991)',
            'additionalLinks': 'http://magazines.russ.ru/vestnik/2002/6/sherbina.html, https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D1%82%D0%BE%D1%80%D1%8B_%D0%BA%D0%BE%D0%BC%D0%BD%D0%B0%D1%82%D1%8B,_%D0%B8%D0%BB%D0%B8_%D0%A1%D0%B5%D0%BD%D1%82%D0%B8%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%BF%D1%83%D1%82%D0%B5%D1%88%D0%B5%D1%81%D1%82%D0%B2%D0%B8%D0%B5_%D0%BD%D0%B0_%D1%80%D0%BE%D0%B4%D0%B8%D0%BD%D1%83, https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D0%B9_%D0%BD%D0%B5_%D0%BF%D0%BE%D1%8D%D1%82, https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%B2%D0%BB%D0%B0%D1%82%D0%BE%D0%B2_(%D1%84%D0%B8%D0%BB%D1%8C%D0%BC)',
            'authorPhoto': {filename: 'brodskyProfilePhoto.jpg'},
            'children': 'Андрей Осипович Басманов, Анастасия Иосифовна Кузнецова, Анна-Александра-Мария Бродская',
            'parents': 'Александр Иванович Бродский (капитан ВМФ СССР, военный фотокорреспондент), Мария Моисеевна Вольперт (бухгалтер)',
            __ref: 'iosifBrodsky',
            'user': 'admin'
        },
        {
            'name.first': 'Пушкин',
            'name.last': 'Александр',
            'patronymic': 'Сергеевич',
            'birthDay': new Date(1799, 5, 6),
            'deathDay': new Date(1837, 1, 10),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'http://www.feb-web.ru/feb/pushkin/default.asp',
            'authorPhoto': {filename: 'pushkinProfilePhoto.jpg'},
            'children': 'Мария Александровна Гартунг, Наталья Александровна Пушкина-Дубельт, Григорий Александрович Пушкин, Александр Александрович Пушкин',
            'parents': 'Сергей Львович Пушкин (поэт-любитель), Надежда Осиповна Ганнибал',
            __ref: 'aleksandrPushkin',
            'user': 'admin'
        },
        {
            'name.last': 'Михаил',
            'name.first': 'Булгаков',
            'patronymic': 'Афанасьевич',
            'birthDay': new Date(1891, 4, 15),
            'deathDay': new Date(1940, 2, 10),
            'birthCountry': 'Российская империя',
            'birthCity': 'Киев',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%83%D0%BB%D0%B3%D0%B0%D0%BA%D0%BE%D0%B2,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%90%D1%84%D0%B0%D0%BD%D0%B0%D1%81%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'bulgakovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Афанасий Иванович Булгаков (профессор Киевской духовной академии), Варвара Михайловна Покровская (преподаватель женской прогимназии)',
            __ref: 'michaelBulgakov',
            'user': 'admin'
        },
        {
            'name.last': 'Николай',
            'name.first': 'Гоголь',
            'patronymic': 'Васильевич',
            'birthDay': new Date(1809, 4, 1),
            'deathDay': new Date(1852, 2, 4),
            'birthCountry': 'Российская империя',
            'birthCity': 'Большие Сорочинцы',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D0%B3%D0%BE%D0%BB%D1%8C,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gogolProfilePhoto.jpeg'},
            'children': '',
            'parents': 'Василий Афанасьевич Гоголь-Яновский (писатель, государственный служащий), Мария Ивановна Косяровская',
            __ref: 'nikolaiGogol',
            'user': 'admin'
        },
        {
            'name.last': 'Максим',
            'name.first': 'Горький',
            'patronymic': '',
            'birthDay': new Date(1868, 2, 28),
            'deathDay': new Date(1936, 5, 18),
            'birthCountry': 'Российская империя',
            'birthCity': 'Нижний Новгород',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC_%D0%93%D0%BE%D1%80%D1%8C%D0%BA%D0%B8%D0%B9',
            'honors': 'Орден Ленина',
            'additionalLinks': 'http://maksim-gorky.ru/',
            'authorPhoto': {filename: 'gorkiiProfilePhoto.jpg'},
            'children': 'Максим Алексеевич Пешков, Зиновий Алексеевич Пешков, Екатерина Алексеевна Пешкова',
            'parents': 'Максим Савватьевич Пешков (столяр), Варвара Васильевна Каширина (мещанка)',
            __ref: 'maksimGorkii',
            'user': 'admin'
        },
        {
            'name.last': 'Сергей',
            'name.first': 'Есенин',
            'patronymic': 'Александрович',
            'birthDay': new Date(1895, 9, 3),
            'deathDay': new Date(1925, 11, 28),
            'birthCountry': 'Российская империя',
            'birthCity': 'Константиново, Рязанская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%95%D1%81%D0%B5%D0%BD%D0%B8%D0%BD,_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'eseninProfilePhoto.jpg'},
            'children': 'Татьяна Сергеевна Есенина, Александр Сергеевич Есенин-Вольпин, Константин Сергеевич Есенин, Юрий Сергеевич Есенин',
            'parents': 'Александр Никитич Есенин (крестьянин), Татьяна Фёдоровна Титова (крестьянка)',
            __ref: 'sergeiEsenin',
            'user': 'admin'
        },
        {
            'name.last': 'Василий',
            'name.first': 'Жуковский',
            'patronymic': 'Андреевич',
            'birthDay': new Date(1868, 2, 28),
            'deathDay': new Date(1936, 5, 18),
            'birthCountry': 'Российская империя',
            'birthCity': 'Мишенское, Тульская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%96%D1%83%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'Орден Белого Орла (1841), императорский орден Святого Равноапостольного Князя Владимира 1 степени (1846), орден Святой Анны 2 степени, Императорский и Царский орден Святого Станислава, орден Железной короны, орден Красного орла, Pour le Mérite (Пруссия), орден Заслуг, Королевский Гвельфский орден, орден Фридриха, орден Церингенского льва (княжество Баден), Родовой орден Белого сокола, орден Нидерландского льва, орден Полярной звезды (Швеция), орден Даннеброг (Дания)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'djukovskiiProfilePhoto.jpg'},
            'children': 'Александра Васильевна Жуковская, Павел Васильевич Жуковский',
            'parents': 'Афанасий Иванович Бунин (помещик), Елизавета Дементьевна Турчанинова (в прошлом пленённая турчанка Сальха); приёмным отцом был Андрей Григорьевич Жуковский',
            __ref: 'vasiliiDjukovskii'
        },
        {
            'name.last': 'Николай',
            'name.first': 'Карамзин',
            'patronymic': 'Михайлович',
            'birthDay': new Date(1766, 11, 12),
            'deathDay': new Date(1826, 5, 3),
            'birthCountry': 'Российская империя',
            'birthCity': 'Знаменское, Симбирская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%B0%D0%BC%D0%B7%D0%B8%D0%BD,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'Императорский орден Святой Анны, императорский орден Святого Равноапостольного Князя Владимира',
            'additionalLinks': '',
            'authorPhoto': {filename: 'karamzinProfilePhoto.jpg'},
            'children': 'Софья Николаевна Карамзина, Наталья Николаевна Карамзина, Екатерина Николаевна Мещерская (Карамзина), Андрей Николаевич Карамзин, Наталья Николаевна Карамзина, Андрей Николаевич Карамзин, Александр Николаевич Карамзин, Николай Николаевич Карамзин, Владимир Николаевич Карамзин, Елизавета Николаевна Карамзина',
            'parents': 'Михаил Егорович Карамзин (отставной капитан, дворянин), Екатерина Петровна Карамзина',
            __ref: 'nikolaiKaramzin'
        },
        {
            'name.last': 'Станислав',
            'name.first': 'Лем',
            'patronymic': '',
            'birthDay': new Date(1921, 8, 12),
            'deathDay': new Date(2006, 2, 27),
            'birthCountry': 'Польша',
            'birthCity': 'Львов',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%BC,_%D0%A1%D1%82%D0%B0%D0%BD%D0%B8%D1%81%D0%BB%D0%B0%D0%B2',
            'honors': 'Орден Белого орла, Орден Возрождения Польши, Орден Знамени Труда, Знак Отличия "Крест Заслуги"',
            'additionalLinks': 'https://lem.pl/',
            'authorPhoto': {filename: 'lemProfilePhoto.jpg'},
            'children': 'Томаш Лем',
            'parents': 'Самуил Лем (врач-отоларинголог), Сабина Воллер',
            __ref: 'stanislavLem',
            'user': 'admin'
        },
        {
            'name.last': 'Антон',
            'name.first': 'Чехов',
            'patronymic': 'Павлович',
            'birthDay': new Date(1860, 0, 29),
            'deathDay': new Date(1904, 6, 15),
            'birthCountry': 'Российская империя',
            'birthCity': 'Таганрог',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A7%D0%B5%D1%85%D0%BE%D0%B2,_%D0%90%D0%BD%D1%82%D0%BE%D0%BD_%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'Императорский и Царский Орден Святого Станислава, медаль «За труды по первой всеобщей переписи населения»',
            'additionalLinks': '',
            'authorPhoto': {filename: 'chehovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Павел Егорович Чехов (владелец бакалейной лавки), Евгения Яковлевна Чехова (Морозова)',
            __ref: 'antonChehov',
            'user': 'admin'
        },
        {
            'name.last': 'Владимир',
            'name.first': 'Маканин',
            'patronymic': 'Семёнович',
            'birthDay': new Date(1937, 2, 13),
            'deathDay': new Date(2017, 10, 1),
            'birthCountry': 'СССР',
            'birthCity': 'Орск',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BA%D0%B0%D0%BD%D0%B8%D0%BD,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден "Знак Почёта" (1984), государственная Премия Российской Федерации, лауреат Госпремии России в области литературы и искусства за 1999 год, лауреат Пушкинской премии фонда Тепфера (ФРГ), лауреат премии «Пенне» (Италия), лауреат литературной премии «Русский Букер» (1993), лауреат литературной премии «Большая книга» за роман «Асан» (2008), лауреат антипремии «НацWorst» в рамках премии «Национальный бестселлер» за роман «Асан» — худшая книга 2008 года, Европейская премия по литературе (2012), литературная премия «Ясная Поляна» в номинации «Современная классика» за книгу «Где сходилось небо с холмами»',
            'additionalLinks': '',
            'authorPhoto': {filename: 'makaninProfilePhoto.jpeg'},
            'children': 'две дочери',
            'parents': 'Владимир Семёнович Маканин (инженер-строитель), Анна Ивановна Маканина (учитель русского языка и литературы)',
            __ref: 'vladimirMakanin'
        },
        {
            'name.last': 'Валентин',
            'name.first': 'Распутин',
            'patronymic': 'Григорьевич',
            'birthDay': new Date(1937, 2, 15),
            'deathDay': new Date(2015, 2, 14),
            'birthCountry': 'СССР',
            'birthCity': 'Усть-Уда, Восточно-Сибирская область',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D0%BF%D1%83%D1%82%D0%B8%D0%BD,_%D0%92%D0%B0%D0%BB%D0%B5%D0%BD%D1%82%D0%B8%D0%BD_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'Герой Социалистического Труда, орден «За заслуги перед Отечеством» III степени (8 марта 2008 года), орден «За заслуги перед Отечеством» IV степени (28 октября 2002 года), орден Александра Невского (1 сентября 2011 года), орден Ленина (16 ноября 1984 года), орден Трудового Красного Знамени (1981), орден «Знак Почёта» (1971), Лауреат Государственной премии Российской Федерации (2013), лауреат премии Президента Российской Федерации в области литературы и искусства (2003), лауреат премии Правительства России за выдающиеся заслуги в области культуры (2010), лауреат Государственной премии СССР (1977, 1987), лауреат премии Иркутского комсомола им. Иосифа Уткина (1968), лауреат премии им. Л. Н. Толстого (1992), лауреат премии Фонда развития культуры и искусства при Комитете культуры Иркутской области (1994), лауреат премии им. Святителя Иннокентия Иркутского (1995), лауреат премии журнала «Сибирь» им. А. В. Зверева, лауреат премии Александра Солженицына (2000), лауреат Литературной премии им. Ф. М. Достоевского (2001), лауреат премии им. Александра Невского «России верные сыны» (2004), лауреат премии «Лучший зарубежный роман года. XXI век» (Китай, 2005), лауреат Всероссийской литературной премии имени Сергея Аксакова (2005), лауреат премии Международного фонда единства православных народов (2011), лауреат премии «Ясная поляна» (2012),',
            'additionalLinks': 'http://vgrasputin.ru/',
            'authorPhoto': {filename: 'rasputinProfilePhoto.jpg'},
            'children': 'Мария Валентиновна Распутина',
            'parents': 'Григорий Никитич Распутин (крестьянин), Нина Ивановна Распутина (крестьянка)',
            __ref: 'valentinRasputin'
        },
        {
            'name.last': 'Роберт',
            'name.first': 'Рождественский (Петкевич)',
            'patronymic': 'Иванович (Станиславович)',
            'birthDay': new Date(1932, 5, 20),
            'deathDay': new Date(1994, 7, 19),
            'birthCountry': 'СССР',
            'birthCity': 'Косиха, Западно-Сибирский край',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%B6%D0%B4%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%A0%D0%BE%D0%B1%D0%B5%D1%80%D1%82_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден Ленина (16 ноября 1984 года), орден Октябрьской Революции (18.06.1982), орден Трудового Красного Знамени, орден «Знак Почёта» (28.10.1967; 23.03.1976), «Золотой венец» Стружских вечеров поэзии (1966), премия Ленинского комсомола (1972), Государственная премия СССР (1979)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'rodjdestvenskiiProfilePhoto.jpg'},
            'children': 'Екатериан Робертовна Рождественская, Ксения Робертовна Рождественская',
            'parents': 'Станислав Никодимович Петкевич (работник ОГПУ(НКВД)), Вера Павловна Фёдорова (директор сельской начальной школы)',
            __ref: 'robertRodjdestvenskii'
        },
        {
            'name.last': 'Аркадий, Борис',
            'name.first': 'Стругацкие',
            'patronymic': 'Натанович, Натанович',
            'birthDay': 'Аркадий (28 августа 1925), Борис (15 апреля 1933)',
            'deathDay': 'Аркадий (12 октября 1991), Борис (19 ноября 2012)',
            'birthCountry': 'Аркадий (Грузия), Борис (СССР)',
            'birthCity': 'Аркадий (Батуми), Борис (Ленинград)',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%82%D1%8C%D1%8F_%D0%A1%D1%82%D1%80%D1%83%D0%B3%D0%B0%D1%86%D0%BA%D0%B8%D0%B5',
            'honors': 'премия "Аэлита" (1981)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'strugazkieProfilePhoto.jpg'},
            'children': 'Аркадий: Мария Аркадьевна Стругацкая; Борис: Андрей Борисович стругацкий',
            'parents': 'Натан Залманович Стругацкий (редактор газеты), Александра Ивановна Литвинчева (школьный учитель)',
            __ref: 'strugazkie'
        },
        {
            'name.last': 'Денис',
            'name.first': 'Фонвизин',
            'patronymic': 'Иванович',
            'birthDay': new Date(1745, 3, 14),
            'deathDay': new Date(1792, 11, 12),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D0%BD%D0%B2%D0%B8%D0%B7%D0%B8%D0%BD,_%D0%94%D0%B5%D0%BD%D0%B8%D1%81_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'fonvizinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Иван Андреевич Фонвизин (статский советник), Екатерина Васильевна Дмитриева-Мамонова',
            __ref: 'denisFonvizin'
        },
        {
            'name.last': 'Даниил',
            'name.first': 'Хармс (Ювачёв)',
            'patronymic': 'Иванович',
            'birthDay': new Date(1905, 11, 30),
            'deathDay': new Date(1942, 1, 2),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A5%D0%B0%D1%80%D0%BC%D1%81,_%D0%94%D0%B0%D0%BD%D0%B8%D0%B8%D0%BB_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'http://d-harms.ru/',
            'authorPhoto': {filename: 'harmsProfilePhoto.jpg'},
            'children': '',
            'parents': 'Иван Павлович Ювачёв (революционер-народоволец, духовный писатель), Надежда Ивановна Колюбакина',
            __ref: 'daniilHarms'
        },
        {
            'name.last': 'Велимир (Виктор)',
            'name.first': 'Хлебников',
            'patronymic': 'Владимирович',
            'birthDay': new Date(1885, 10, 9),
            'deathDay': new Date(1922, 5, 28),
            'birthCountry': 'Российская империя',
            'birthCity': 'Малодербетовский улус, Астраханская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%A5%D0%BB%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2,_%D0%92%D0%B5%D0%BB%D0%B8%D0%BC%D0%B8%D1%80',
            'honors': '',
            'additionalLinks': 'http://hlebnikov.ru/',
            'authorPhoto': {filename: 'hlebnikovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Владимир Алексеевич Хлебников (орнитолог), Екатерина Николаевна Вербицкая (историк)',
            __ref: 'velimirHlebnikov'
        },
        // 
        {
            "name.last": "Авенариус",
            "name.first": "Вильгельм",
            "patronymic": "Петрович",
            'birthDay': new Date(1839, 11, 10),
            'deathDay': new Date(1923, 12, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Царское село',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D1%83%D1%81,_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'avenariusProfilePhoto.png'},
            'children': '',
            'parents': 'Пётр Александрович Авенариус (лютеранский пастор), Генриетта Андреевна Гамельман (дочь лютеранского пастора)',
          },
          {
            "name.last": "Аркадий",
            "name.first": "Аверченко",
            "patronymic": "Тимофеевич",
            'birthDay': new Date(1880, 4, 27),
            'deathDay': new Date(1925, 4, 12),
            'birthCountry': 'Российская империя',
            'birthCity': 'Севастополь',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D0%B5%D1%80%D1%87%D0%B5%D0%BD%D0%BA%D0%BE,_%D0%90%D1%80%D0%BA%D0%B0%D0%B4%D0%B8%D0%B9_%D0%A2%D0%B8%D0%BC%D0%BE%D1%84%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'http://www.arkadiyaverchenko.ru/',
            'authorPhoto': {filename: 'averchenkoProfilePhoto.jpg'},
            'children': '',
            'parents': 'Тимофей Петрович Аверченко (купец), Сусанна Павловна Софронова (дочь солдата)',
},
          {
            "name.last": "Николай",
            "name.first": "Агнивцев",
            "patronymic": "Яковлевич",
            'birthDay': new Date(1888, 5, 20),
            'deathDay': new Date(1932, 11, 29),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%B3%D0%BD%D0%B8%D0%B2%D1%86%D0%B5%D0%B2,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'agnivtcevProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.last": "Сергей",
            "name.first": "Аксаков",
            "patronymic": "Тимофеевич",
            'birthDay': new Date(1791, 11, 1),
            'deathDay': new Date(1859, 6, 12),
            'birthCountry': 'Российская империя',
            'birthCity': 'Уфа',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BA%D1%81%D0%B0%D0%BA%D0%BE%D0%B2,_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%A2%D0%B8%D0%BC%D0%BE%D1%84%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'aksakovProfilePhoto.jpg'},
            'children': 'Константин Сергеевич Аксаков, Иван Сергеевич Аксаков, Вера Ивановна Аксакова',
            'parents': 'Тимофей Степанович Аксаков (прокурор земского суда), Мария Николаевна Зубова (дочь генерал-губернатора)',

          },
          {
            "name.last": "Александра",
            "name.first": "Анненская",
            "patronymic": "Никитична",
            'birthDay': new Date(1840, 8, 11),
            'deathDay': new Date(1915, 6, 19),
            'birthCountry': 'Российская империя',
            'birthCity': 'Сивцево, Псковская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%BD%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%B0_%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B8%D1%87%D0%BD%D0%B0',
            'honors': '',
            'additionalLinks': 'http://annensky.lib.ru/names/nf&an/an_name.htm',
            'authorPhoto': {filename: 'annenskayaProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.last": "Анненский",
            "name.first": "Иннокентий",
            "patronymic": "Фёдорович",
            'birthDay': new Date(1855, 10, 1),
            'deathDay': new Date(1909, 13, 13),
            'birthCountry': 'Российская империя',
            'birthCity': 'Омск',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%BD%D0%B5%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%98%D0%BD%D0%BD%D0%BE%D0%BA%D0%B5%D0%BD%D1%82%D0%B8%D0%B9_%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'annenskiiProfilePhoto.jpg'},
            'children': '',
            'parents': 'Фёдор Николаевич Анненский (чиновник), Наталья Петровна Анненская',

          },
          {
            "name.last": "Леонид",
            "name.first": "Андреев",
            "patronymic": "Николаевич",
            'birthDay': new Date(1871, 9, 21),
            'deathDay': new Date(1919, 10, 12),
            'birthCountry': 'Российская империя',
            'birthCity': 'Орёл',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2,_%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'https://project1917.ru/heroes/leonid-andreev, http://www.andreev-museum.ru/, http://leonidandreev.ru/',
            'authorPhoto': {filename: 'andreevProfilePhoto.jpg'},
            'children': 'Даниил Леонидович Андреев',
            'parents': 'Николай Иваночив Андреев (землемер-таксатор), Анастасия Николаевна Пацковская (дочь польского помещика)',

          },
          {
            "name.last": "Алексей",
            "name.first": "Апухтин",
            "patronymic": "Николаевич",
            'birthDay': new Date(1840, 12, 27),
            'deathDay': new Date(1893, 9, 29),
            'birthCountry': 'Российская империя',
            'birthCity': 'Болхов, Орловская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BF%D1%83%D1%85%D1%82%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'apuhtinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Николай Фёдорович Апухтин (дворянин), Мария Андреевна Желябужская',

          },
          {
            "name.last": "Владимир",
            "name.first": "Арсеньев",
            "patronymic": "Клавдиевич",
            'birthDay': new Date(1872, 10, 10),
            'deathDay': new Date(1930, 10, 4),
            'birthCountry': 'Российская империя',
            'birthCity': 'Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D1%80%D1%81%D0%B5%D0%BD%D1%8C%D0%B5%D0%B2,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9A%D0%BB%D0%B0%D0%B2%D0%B4%D0%B8%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'arsenyevProfilePhoto.jpg'},
            'children': '',
            'parents': 'Клавдий Фёдорович Арсеньев (тверской мещанин), Агриппина Филлиповна Лодыгина (дворовая девка)',

          },
          {
            "name.last": "Михаил",
            "name.first": "Арцыбашев",
            "patronymic": "Петрович",
            'birthDay': new Date(1878, 12, 5),
            'deathDay': new Date(1927, 4, 3),
            'birthCountry': 'Российская империя',
            'birthCity': 'Доброславовка, Харьковская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D1%80%D1%86%D1%8B%D0%B1%D0%B0%D1%88%D0%B5%D0%B2,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'https://www.imdb.com/name/nm1863727/',
            'authorPhoto': {filename: 'artcibshevProfilePhoto.jpg'},
            'children': 'Борис Михайлович Арцыбашев',
            'parents': 'Пётр Арцыбашев (уездный начальник полиции)',

          },
          {
            "name.last": "Константин",
            "name.first": "Бальмонт",
            "patronymic": "Дмитриевич",
            'birthDay': new Date(1867, 7, 15),
            'deathDay': new Date(1942, 13, 23),
            'birthCountry': 'Российская империя',
            'birthCity': 'Гумнищи, Владимирская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%BB%D1%8C%D0%BC%D0%BE%D0%BD%D1%82,_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'balmontProfilePhoto.jpg'},
            'children': 'Мирра Константиновна Бальмонт, Нина Константиновна Бальмонт-Бруни, Георгий Константинович Бальмонт, Светлана Константиновна Бальмонт',
            'parents': 'Дмитрий Константинович Бальмонт (мировой судья), Вера Николаевна Лебедева (дочь полковника)',

          },
          {
            "name.last": "Евгений",
            "name.first": "Баратынский",
            "patronymic": "Абрамович",
            'birthDay': new Date(1800, 4, 2),
            'deathDay': new Date(1844, 8, 11),
            'birthCountry': 'Российская империя',
            'birthCity': 'Вяжля, Тамбовская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%B0%D1%82%D1%8B%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%90%D0%B1%D1%80%D0%B0%D0%BC%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'baratynskiiProfilePhoto.jpg'},
            'children': 'Лев Евгеньевич Баратынский',
            'parents': 'Абрам Андреевич Баратынский (отставной генерал-лейтенант), Александра Фёдоровна Черепанова (дочь коменданта Петропавловской крепости, фрейлина императрицы Марии Фёдоровны)',

          },
          {
            "name.last": "Иван",
            "name.first": "Барков",
            "patronymic": "Семенович",
            'birthDay': new Date(1732),
            'deathDay': new Date(1768),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%BA%D0%BE%D0%B2,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'barkovProfilePhoto.jpg'},
            'children': '',
            'parents': 'отец - священник',

          },
          {
            "name.last": "Константин",
            "name.first": "Батюшков",
            "patronymic": "Николаевич",
            'birthDay': new Date(1787, 6, 29),
            'deathDay': new Date(1855, 8, 19),
            'birthCountry': 'Российская империя',
            'birthCity': 'Вологда',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%82%D1%8E%D1%88%D0%BA%D0%BE%D0%B2,_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'batyushkovProfilePhoto.JPG'},
            'children': '',
            'parents': 'Николай Львович Батюшков (дворянин), Александра Григорьевна Бердяева',

          },
          {
            "name.last": "Виссарион",
            "name.first": "Белинский",
            "patronymic": "Григорьевич",
            'birthDay': new Date(1811, 7, 11),
            'deathDay': new Date(1848, 6, 26),
            'birthCountry': 'Российская империя',
            'birthCity': 'крепость Свеаборг, Великое княжество Финляндское',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D0%BB%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%B8%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%BE%D0%BD_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'belinskiiProfilePhoto.jpg'},
            'children': '',
            'parents': 'Григорий Никифорович Белынский (уездный лекарь)',

          },
          {
            "name.last": "Андрей",
            "name.first": "Белый",
            "patronymic": "",
            'birthDay': new Date(1880, 11, 26),
            'deathDay': new Date(1934, 2, 8),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%91%D0%B5%D0%BB%D1%8B%D0%B9',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'belyyProfilePhoto.jpg'},
            'children': '',
            'parents': 'Николай Васильевич Бугаев (декан физмата МГУ), Александра Дмитриевна Егорова',

          },
          {
            "name.last": "Павел",
            "name.first": "Беспощадный",
            "patronymic": "Григорьевич",
            'birthDay': new Date(1895, 8, 12),
            'deathDay': new Date(1968, 6, 25),
            'birthCountry': 'Российская империя',
            'birthCity': 'Всеславль, Смоленская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BF%D0%BE%D1%89%D0%B0%D0%B4%D0%BD%D1%8B%D0%B9,_%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'Орден Ленина, орден Трудового красного знамени (2), Почётный шахтёр СССР, Почётный гражденин Горловки',
            'additionalLinks': '',
            'authorPhoto': {filename: 'bespotschadnyyProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.last": "Александр",
            "name.first": "Бестужев",
            "patronymic": "Александрович",
            'birthDay': new Date(1797, 12, 3),
            'deathDay': new Date(1837, 9, 19),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D1%82%D1%83%D0%B6%D0%B5%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'https://www.kino-teatr.ru/kino/movie/sov/6126/annot/, http://kemenkiri.narod.ru/VDIABestujev.pdf',
            'authorPhoto': {filename: 'bestudgevProfilePhoto.jpg'},
            'children': '',
            'parents': 'Александр Федосеевич Бестужев (просветитель-демократ, писатель), Прасковья Михайловна Бестужева',

          },
          {
            "name.last": "Владимир",
            "name.first": "Билль-Белоцерковский",
            "patronymic": "Наумович",
            'birthDay': new Date(1884, 13, 28),
            'deathDay': new Date(1970),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'velotserkovskiiProfilePhoto.png'},
            'children': 'Вадим Владимирович Белоцерковский',
            'parents': 'отец - еврей, лесничий, мелкий маклер',

          },
          {
            "name.last": "Александр",
            "name.first": "Блок",
            "patronymic": "Александрович",
            'birthDay': new Date(1880, 12, 28),
            'deathDay': new Date(1921, 9, 7),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%BA,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'blockProfilePhoto.jpg'},
            'children': 'Александра Павловна Люш',
            'parents': 'Александр Львович Блок (юрист, профессор Варшавского университета), Александра Андреева Бекетова (дочь ректора СпбГУ)',

          },
          {
            "name.last": "Ипполит",
            "name.first": "Богданович",
            "patronymic": "Фёдорович",
            'birthDay': new Date(1744, 2, 3),
            'deathDay': new Date(1803, 2, 18),
            'birthCountry': 'Российская империя',
            'birthCity': 'Переволочна, Киевская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%B3%D0%B4%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87,_%D0%98%D0%BF%D0%BF%D0%BE%D0%BB%D0%B8%D1%82_%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'bogdanovichProfilePhoto.jpg'},
            'children': '',
            'parents': 'Фёдор Богданович (бедный мелкопоместный дворянин)',

          },
          {
            "name.last": "Валерий",
            "name.first": "Брюсов",
            "patronymic": "Яковлевич",
            'birthDay': new Date(1873, 13, 13),
            'deathDay': new Date(1924, 11, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%80%D1%8E%D1%81%D0%BE%D0%B2,_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B9_%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'brusovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Яков Кузьмич Брюсов',

          },
          {
            "name.last": "Фаддей",
            "name.first": "Булгарин",
            "patronymic": "Венедиктович",
            'birthDay': new Date(1789, 8, 5),
            'deathDay': new Date(1859, 10, 13),
            'birthCountry': 'Российская империя',
            'birthCity': 'Перышево, Великое княжество Литовское',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%83%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D0%BD,_%D0%A4%D0%B0%D0%B4%D0%B4%D0%B5%D0%B9_%D0%92%D0%B5%D0%BD%D0%B5%D0%B4%D0%B8%D0%BA%D1%82%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'bulgarinProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.last": "Иван",
            "name.first": "Бунин",
            "patronymic": "Алексеевич",
            'birthDay': new Date(1870, 11, 22),
            'deathDay': new Date(1953, 12, 8),
            'birthCountry': 'Российская империя',
            'birthCity': 'Воронеж',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%83%D0%BD%D0%B8%D0%BD,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'Пушкинская премия (1901, 1903, 1909), Нобелевская премия по литературе (1933)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'buninProfilePhoto.jpg'},
            'children': 'Николай Иванович Бунин',
            'parents': 'Алексей Николаевич Бунин (помещик), Людмила Александровна Чубарова',

          },
          {
            "name.last": "Давид",
            "name.first": "Бурлюк",
            "patronymic": "Давидович",
            'birthDay': new Date(1882, 8, 21),
            'deathDay': new Date(1967, 2, 15),
            'birthCountry': 'Российская империя',
            'birthCity': 'Семиротовка, Харьковская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%91%D1%83%D1%80%D0%BB%D1%8E%D0%BA,_%D0%94%D0%B0%D0%B2%D0%B8%D0%B4_%D0%94%D0%B0%D0%B2%D0%B8%D0%B4%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'burlyukProfilePhoto.jpg'},
            'children': '',
            'parents': 'Бурлюк Давид Давидович (агроном-самоучка)',

          },
          {
            "name.last": "Дмитрий",
            "name.first": "Веневитинов",
            "patronymic": "Владимирович",
            'birthDay': new Date(1805, 10, 26),
            'deathDay': new Date(1827, 4, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BD%D0%B5%D0%B2%D0%B8%D1%82%D0%B8%D0%BD%D0%BE%D0%B2,_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'venevitovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Владимир Петрович Веневитинов (отставной прапорщик), Анна Николаевна Оболенская (дальняя родственница А.С. Пушкин, княжеское происхождение)',

          },
          {
            "name.last": "Максимилиан",
            "name.first": "Волошин",
            "patronymic": "Александрович",
            'birthDay': new Date(1877, 6, 28),
            'deathDay': new Date(1932, 9, 11),
            'birthCountry': 'Российская империя',
            'birthCity': 'Киев',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%92%D0%BE%D0%BB%D0%BE%D1%88%D0%B8%D0%BD,_%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%B8%D0%BB%D0%B8%D0%B0%D0%BD_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'voloshinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Александр Волошин (юрист, коллежский советник), Елена Оттобальдовна Глазер',

          },
          {
            "name.last": "Петр",
            "name.first": "Вяземский",
            "patronymic": "Андреевич",
            'birthDay': new Date(1792, 8, 23),
            'deathDay': new Date(1878, 12, 22),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%92%D1%8F%D0%B7%D0%B5%D0%BC%D1%81%D0%BA%D0%B8%D0%B9,_%D0%9F%D1%91%D1%82%D1%80_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'vyazemskiiProfilePhoto.jpg'},
            'children': 'Павел Петрович Вяземский',
            'parents': "Андрей Иванович Вяземский (князь, тайный советник), Дженни О'Рейли",

          },
          {
            "name.last": "Николай",
            "name.first": "Гарин-Михайловский",
            "patronymic": "Георгиевич",
            'birthDay': new Date(1852, 3, 20),
            'deathDay': new Date(1906, 13, 10),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D1%80%D0%B8%D0%BD-%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'garinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Георгий Антонович Михайловский (дворянин, улан), Глафира Николаевна Цветинович (дворянка)',

          },
          {
            "name.last": "Всеволод",
            "name.first": "Гаршин",
            "patronymic": "Михайлович",
            'birthDay': new Date(1855, 3, 14),
            'deathDay': new Date(1888, 5, 5),
            'birthCountry': 'Российская империя',
            'birthCity': 'Приятная Долина, екатеринославская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D1%80%D1%88%D0%B8%D0%BD,_%D0%92%D1%81%D0%B5%D0%B2%D0%BE%D0%BB%D0%BE%D0%B4_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'garshinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Михаил Егорович Гаршин (офицер)',

          },
          {
            "name.last": "Александр",
            "name.first": "Герцен",
            "patronymic": "Иванович",
            'birthDay': new Date(1812, 5, 6),
            'deathDay': new Date(1870, 2, 21),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D1%80%D1%86%D0%B5%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gertsenProfilePhoto.jpg'},
            'children': 'Александр Александрович Герцен',
            'parents': 'Иван Алексеевич Яковлев (помещик), Генриетта-Вильгельмина-Луиза Гааг (дочь мелкого чиновника)',

          },
          {
            "name.last": "Зинаида",
            "name.first": "Гиппиус",
            "patronymic": "Николаевна",
            'birthDay': new Date(1869, 12, 20),
            'deathDay': new Date(1945, 10, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Белёв, Тульская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D0%BF%D0%BF%D0%B8%D1%83%D1%81,_%D0%97%D0%B8%D0%BD%D0%B0%D0%B8%D0%B4%D0%B0_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gippiusProfilePhoto.jpg'},
            'children': '',
            'parents': 'Николай Романович Гиппиус (юрист, обер-прокурор), Анастасия Васильевна Степанова (дочь обер-полицмейстера)',

          },
          {
            "name.last": "Николай",
            "name.first": "Гнедич",
            "patronymic": "Иванович",
            'birthDay': new Date(1784, 3, 13),
            'deathDay': new Date(1833, 3, 15),
            'birthCountry': 'Российская империя',
            'birthCity': 'Полтава',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%BD%D0%B5%D0%B4%D0%B8%D1%87,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gnedichProfilePhoto.jpg'},
            'children': '',
            'parents': 'Иван Петрович Гнедич (потомок старинного небогатого дворянского рода)',

          },
          {
            "name.last": "Василиск",
            "name.first": "Гнедов",
            "patronymic": "",
            'birthDay': new Date(1890, 4, 18),
            'deathDay': new Date(1978, 12, 5),
            'birthCountry': 'Российская империя',
            'birthCity': 'слобода Маньково-Берёзовская, область Войска Донского',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%BD%D0%B5%D0%B4%D0%BE%D0%B2,_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D1%81%D0%BA',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gnedovProfilePhoto.jpg'},
            'children': '',
            'parents': 'отец - мещанин, мать - крестьянка',

          },
          {
            "name.last": "Сергей",
            "name.first": "Городецкий",
            "patronymic": "Митрофанович",
            'birthDay': new Date(1884, 2, 17),
            'deathDay': new Date(1967, 7, 7),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B5%D1%86%D0%BA%D0%B8%D0%B9,_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%9C%D0%B8%D1%82%D1%80%D0%BE%D1%84%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'знак Почёта',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gorodetskiiProfilePhoto.jpg'},
            'children': 'Рогнеда Городецкая-Бирюкова',
            'parents': 'Митрофан Иванович Городецкий (писатель-этнограф)',

          },
          {
            "name.last": "Иван",
            "name.first": "Гончаров",
            "patronymic": "Александрович",
            'birthDay': new Date(1812, 7, 18),
            'deathDay': new Date(1891, 10, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Симбирск',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D0%BD%D1%87%D0%B0%D1%80%D0%BE%D0%B2,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'goncharovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Александр Иванович Гончаров (купец), Авдотья Матвеевна Шахторина',

          },
          {
            "name.last": "Александр",
            "name.first": "Грибоедов",
            "patronymic": "Сергеевич",
            'birthDay': new Date(1795, 2, 15),
            'deathDay': new Date(1829, 3, 11),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B8%D0%B1%D0%BE%D0%B5%D0%B4%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'императорский орден Святой Анны, орден Льва и Солнца',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gribiyedovProfilePhoto.jpg'},
            'children': '',
            'parents': ' Сергей Иванович Грибоедов (отставной секунд-майор), Анастасия Фёдоровна Грибоедова',

          },
          {
            "name.last": "Дмитрий",
            "name.first": "Григорович",
            "patronymic": "Васильевич",
            'birthDay': new Date(1822, 4, 31),
            'deathDay': new Date(1900, 2, 3),
            'birthCountry': 'Российская империя',
            'birthCity': 'Никольское-на-Черемшане, Симбирская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%87,_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'grigorovichProfilePhoto.jpg'},
            'children': '',
            'parents': 'Василий Григорович (помещик, отставной гусар), Сидония де Вармон (дочь казнённого роялиста)',

          },
          {
            "name.last": "Аполлон",
            "name.first": "Григорьев",
            "patronymic": "Александрович",
            'birthDay': new Date(1822, 8, 28),
            'deathDay': new Date(1864, 11, 7),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2,_%D0%90%D0%BF%D0%BE%D0%BB%D0%BB%D0%BE%D0%BD_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'grigoryevProfilePhoto.jpg'},
            'children': '',
            'parents': 'Александр Иванович Григорьев (титулярный советник), мать - дочь крепостного кучера',

          },
          {
            "name.last": "Александр",
            "name.first": "Грин",
            "patronymic": "Степанович",
            'birthDay': new Date(1880, 9, 23),
            'deathDay': new Date(1932, 8, 8),
            'birthCountry': 'Российская империя',
            'birthCity': 'Слободской, Вятская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D1%82%D0%B5%D0%BF%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'grinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Стефан Гриневский (польский шляхтич), Анна Степановна Лепкова (медсестра)',
          },
          {
            "name.last": "Николай",
            "name.first": "Гумилёв",
            "patronymic": "Степанович",
            'birthDay': new Date(1886, 5, 15),
            'deathDay': new Date(1921, 9, 26),
            'birthCountry': 'Российская империя',
            'birthCity': 'Кронштадт',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%93%D1%83%D0%BC%D0%B8%D0%BB%D1%91%D0%B2,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%A1%D1%82%D0%B5%D0%BF%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'императорский орден Святого Станислава, знак отличия Военного ордена',
            'additionalLinks': '',
            'authorPhoto': {filename: 'gumilevProfilePhoto.jpg'},
            'children': 'Лев Николаевич Гумилёв',
            'parents': 'Стапан Яковлевич Гумилёв (корабельный врач), Анна Ивановна Львова',

          },
          {
            "name.last": "Денис",
            "name.first": "Давыдов",
            "patronymic": "Васильевич",
            'birthDay': new Date(1784, 8, 27),
            'deathDay': new Date(1839, 6, 5),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%94%D0%B0%D0%B2%D1%8B%D0%B4%D0%BE%D0%B2,_%D0%94%D0%B5%D0%BD%D0%B8%D1%81_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святого Георгия, орден Святого Владимира (3), императорский орден Святой Анны (2), орден Virtuti Militari, орден pour le Merite, крест «За победу при Прейсиш-Эйлау», золотое оружие "За храбрость"',
            'additionalLinks': '',
            'authorPhoto': {filename: 'davydovProfilePhoto.jpg'},
            'children': 'Вадим Денисович Давыдов',
            'parents': 'Василий Денисович Давыдов (бригадир А.В. Суворова, дворянин), мать - дочь енерал-губернатора',

          },
          {
            "name.last": "Гавриил",
            "name.first": "Державин",
            "patronymic": "Романович",
            'birthDay': new Date(1743, 8, 14),
            'deathDay': new Date(1816, 8, 20),
            'birthCountry': 'Российская империя',
            'birthCity': 'Сокуры, Казанская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%B8%D0%BD,_%D0%93%D0%B0%D0%B2%D1%80%D0%B8%D0%B8%D0%BB_%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святого Александра Невского, орден Святого Владимира (2), орден Святой Анны, Мальтийский крест',
            'additionalLinks': '',
            'authorPhoto': {filename: 'derdjavinProfilePhoto.jpg'},
            'children': '',
            'parents': 'Роман Николаевич Державин (секунд-майор, дворянин), Фёкла Андреевна Козлова',

          },
          {
            "name.last": "Иван",
            "name.first": "Дмитриев",
            "patronymic": "Иванович",
            'birthDay': new Date(1760, 10, 21),
            'deathDay': new Date(1837, 11, 15),
            'birthCountry': 'Российская империя',
            'birthCity': 'Богородицкое, Казанская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святой Анны, орден Александра Невского, орден Святого Равноапостольного князя Владимира',
            'additionalLinks': '',
            'authorPhoto': {filename: 'dmitrievProfilePhoto.jpg'},
            'children': '',
            'parents': 'Иван Гавриилович Дмитриев (дворянин), Екатерина Афанасьевна Бекетова',

          },
          {
            "name.last": "Фёдор",
            "name.first": "Достоевский",
            "patronymic": "Михайлович",
            'birthDay': new Date(1821, 12, 11),
            'deathDay': new Date(1881, 3, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': 'http://curlie.org//World/Russian/%D0%98%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%BE/%D0%9B%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D1%8B/%D0%94/%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_%D0%A4%D0%B5%D0%B4%D0%BE%D1%80_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87/',
            'authorPhoto': {filename: 'dostoyevskiiProfilePhoto.jpg'},
            'children': 'Любовь Фёдоровна Достоевская, Алексей Фёдорович Достоевский, Софья Фёдоровна Достоевская, Фёдор Фёдорович Достоевский',
            'parents': 'Михаил Андреевич Достоевский (штаб-лекарь), Мария Фёдоровна Нечаева (дочь купца 3-ей гильдии)',

          },
          {
            "name.last": "Михаил",
            "name.first": "Зенкевич",
            "patronymic": "Александрович",
            'birthDay': new Date(1886, 6, 21),
            'deathDay': new Date(1973, 10, 14),
            'birthCountry': 'Российская империя',
            'birthCity': 'Николаевский, Саратовская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%BD%D0%BA%D0%B5%D0%B2%D0%B8%D1%87,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'zenkevichProfilePhoto.jpg'},
            'children': '',
            'parents': 'отец - учитель, мать - учительница',

          },
          {
            "name.last": "Михаил",
            "name.first": "Зощенко",
            "patronymic": "Михайлович",
            'birthDay': new Date(1894, 9, 10),
            'deathDay': new Date(1958, 8, 22),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%97%D0%BE%D1%89%D0%B5%D0%BD%D0%BA%D0%BE,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден трудового красного Знамени, орден Святого Станислава (2), орден Святой Анны (2), медаль «За доблестный труд в Великой Отечественной войне 1941—1945 гг.», орден Святого Владимира',
            'additionalLinks': '',
            'authorPhoto': {filename: 'zotschenkoProfilePhoto.jpg'},
            'children': 'Валерий Михайлович Зощенко',
            'parents': 'Михаил Иванович Зощенко (художник), Елена Осиповна Сурина (дворянка, актриса)',

          },
          {
            "name.last": "Николай",
            "name.first": "Клюев",
            "patronymic": "Алексеевич",
            'birthDay': new Date(1884, 11, 22),
            'deathDay': new Date(1937, 11, 25),
            'birthCountry': 'Российская империя',
            'birthCity': 'Коштуги, Олонецкая губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D1%8E%D0%B5%D0%B2,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'klyuyevProfilePhoto.jpg'},
            'children': '',
            'parents': 'Алексей Тимофеевич Клюев (урядник), Прасковья Дмитриевна Клюева (сказительница, плакальщица)',

          },
          {
            "name.last": "Алексей",
            "name.first": "Кольцов",
            "patronymic": "Васильевич",
            'birthDay': new Date(1809, 11, 15),
            'deathDay': new Date(1842, 12, 10),
            'birthCountry': 'Российская империя',
            'birthCity': 'Воронеж',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BB%D1%8C%D1%86%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'koltsovProfilePhoto.png'},
            'children': '',
            'parents': 'Василий Петрович Кольцов (скупщик, торговец скотом), Прасковья Ивановна Кольцова',

          },
          {
            "name.last": "Владимир",
            "name.first": "Короленко",
            "patronymic": "Галактионович",
            'birthDay': new Date(1853, 8, 27),
            'deathDay': new Date(1921, 13,25),
            'birthCountry': 'Российская империя',
            'birthCity': 'Житомир',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%BB%D0%B5%D0%BD%D0%BA%D0%BE,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%93%D0%B0%D0%BB%D0%B0%D0%BA%D1%82%D0%B8%D0%BE%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'korolenkoProfilePhoto.jpg'},
            'children': 'Наталья Владимировна Ляхович, Соья Владимировна Короленко',
            'parents': 'Галактион Афанасьевич Короленко (уездный судья, коллежский ассесор), Эвелина Иосифовна Короленко',

          },
          {
            "name.last": "Алексей",
            "name.first": "Кручёных",
            "patronymic": "Елисеевич",
            'birthDay': new Date(1886, 3, 21),
            'deathDay': new Date(1968, 7, 17),
            'birthCountry': 'Российская империя',
            'birthCity': 'Оливское, Херсонская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%83%D1%87%D1%91%D0%BD%D1%8B%D1%85,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%95%D0%BB%D0%B8%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'kruchenyhProfilePhoto.jpg'},
            'children': '',
            'parents': 'отец - крестьянин, мать - крестьянка',

          },
          {
            "name.last": "Иван",
            "name.first": "Крылов",
            "patronymic": "Андреевич",
            'birthDay': new Date(1769, 3, 13),
            'deathDay': new Date(1844, 12, 21),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%8B%D0%BB%D0%BE%D0%B2,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святого Станислава, орден Святой Анны',
            'additionalLinks': '',
            'authorPhoto': {filename: 'krylovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Андрей Прохорович Крылов (капитан), Мария Алексеевна Крылова',

          },
          {
            "name.last": "Фёдор",
            "name.first": "Крюков",
            "patronymic": "Дмитриевич",
            'birthDay': new Date(1870, 3, 14),
            'deathDay': new Date(1920, 4, 4),
            'birthCountry': 'Российская империя',
            'birthCity': 'Глазуновская, Область войска Донского',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%8E%D0%BA%D0%BE%D0%B2,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святой Анны, орден Святого Станислава',
            'additionalLinks': '',
            'authorPhoto': {filename: 'kryukovProfilePhoto.jpeg'},
            'children': '',
            'parents': 'отец - атаман, мать - донская дворянка',

          },
          {
            "name.last": "Михаил",
            "name.first": "Кузмин",
            "patronymic": "Алексеевич",
            'birthDay': new Date(1872, 11, 18),
            'deathDay': new Date(1936, 4, 1),
            'birthCountry': 'Российская империя',
            'birthCity': 'Ярославль',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B7%D0%BC%D0%B8%D0%BD,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'kuzminProfilePhoto.jpg'},
            'children': '',
            'parents': 'Алексей Алексеевич Кузмин (дворянин, морской офицер), Надежда Дмитриевна Фёдорова',

          },
          {
            "name.last": "Александр",
            "name.first": "Куприн",
            "patronymic": "Иванович",
            'birthDay': new Date(1870, 10, 7),
            'deathDay': new Date(1938, 9, 25),
            'birthCountry': 'Российская империя',
            'birthCity': 'Наровчат, Пензенская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%BF%D1%80%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'kuprinProfilePhoto.jpg'},
            'children': 'Лидия Александровна Куприна, Ксения Александровна Куприна, Зинаида Александровна Куприна',
            'parents': 'Иван Иванович Куприн (дворянин, чиновник), Любовь Алексеевна Кулунчакова (дворянка)',

          },
          {
            "name.last": "Константин",
            "name.first": "Романов",
            "patronymic": "Константинович",
            'birthDay': new Date(1858, 9, 22),
            'deathDay': new Date(1915, 7, 15),
            'birthCountry': 'Российская империя',
            'birthCity': 'Стрельна',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'орден Святого Андрея Первозванного, орден Святого Александра Невского, орден Святой Анны, орден Белого орла, орден Святого Станислава, орден Святого Георгия, медаль "В память русско-турецкой войны", орден Святого Владимира и мн., мн. др.',
            'additionalLinks': '',
            'authorPhoto': {filename: 'romanovProfilePhoto.jpg'},
            'children': 'Иоанн Константинович Романов, Гавриил Константинович Романов, Татьяна Константиновна Романова, Константин Константинович Романов, Олег Константинович романов, Игорь Константинович Романов, Георгий Константинович Романов, Наталия Константиновна Романова, Вера Константиновна Романова',
            'parents': 'Константин Николаевич Романов (великий князь), Александра иосифовна Романова (эрнестинская принцесса)',
            'user': 'admin'
          },
          {
            "name.last": "Михаил",
            "name.first": "Лермонтов",
            "patronymic": "Юрьевич",
            'birthDay': new Date(1814, 11, 15),
            'deathDay': new Date(1841, 8, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D1%80%D0%BC%D0%BE%D0%BD%D1%82%D0%BE%D0%B2,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%AE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'lermontovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Юрий Петрович Лермонтов (капитан), Мария Михайловна Арсеньева',

          },
          {
            "name.last": "Леонид",
            "name.first": "Леонов",
            "patronymic": "Максимович",
            'birthDay': new Date(1899, 6, 31),
            'deathDay': new Date(1994, 9, 8),
            'birthCountry': 'Российская империя',
            'birthCity': 'Москва',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%BE%D0%BD%D0%BE%D0%B2,_%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'номинация на Нобелевскую премию по литературе (1949, 1950), Сталинская премия, Ленинская премия, государственная премия СССР, премия им. Л.Н. Толстого и мн. др.',
            'additionalLinks': '',
            'authorPhoto': {filename: 'leonovProfilePhoto.jpg'},
            'children': '',
            'parents': 'Максим Леонович Леонов (поэт)',

          },
          {
            "name.last": "Николай",
            "name.first": "Лесков",
            "patronymic": "Семёнович",
            'birthDay': new Date(1831, 3, 16),
            'deathDay': new Date(1895, 4, 5),
            'birthCountry': 'Российская империя',
            'birthCity': 'Горохово, Орловская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D1%81%D0%BA%D0%BE%D0%B2,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'leskovProfilePhoto.jpg'},
            'children': 'Дмитрий Николаевич Лесков, Вера Николаевна Лескова, Андрей Николаевич Лесков',
            'parents': 'Семён Дмитриевич Лесков (следователь), Мария Петровна Алферьева (дворянка)',

          },
          {
            "name.last": "Михаил",
            "name.first": "Ломоносов",
            "patronymic": "Васильевич",
            'birthDay': new Date(1711, 12, 19),
            'deathDay': new Date(1765, 5, 15),
            'birthCountry': 'Русское царство',
            'birthCity': 'Мишанинская (сейчас - Ломоносово), Архангелогородская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%BC%D0%BE%D0%BD%D0%BE%D1%81%D0%BE%D0%B2,_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'lomonosovProfilePhoto.jpg'},
            'children': 'Елена Михайловна Ломоносова',
            'parents': 'Василий Дорофеевич Ломоносов (помор), Елена Ивановна Сивкова (дочь просвирницы)',

          },
          {
            "name.last": "Мирра",
            "name.first": "Лохвицкая",
            "patronymic": "Александровна",
            'birthDay': new Date(1869, 13, 1),
            'deathDay': new Date(1905, 10, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D1%85%D0%B2%D0%B8%D1%86%D0%BA%D0%B0%D1%8F,_%D0%9C%D0%B8%D1%80%D1%80%D0%B0_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%BD%D0%B0',
            'honors': 'Пушкинская премия (1897, 1905)',
            'additionalLinks': '',
            'authorPhoto': {filename: 'lohvitskayaProfilePhoto.jpg'},
            'children': 'Михаил, Евгений, Владимир, Измаил, Валерий',
            'parents': 'Александр Владимирович Лохвицкий (адвокат), Варвара Александровна Гойер',

          },
          {
            "name.last": "Осип",
            "name.first": "Мандельштам",
            "patronymic": "Эмильевич",
            'birthDay': new Date(1891, 2, 15),
            'deathDay': new Date(1938, 13, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Варшава',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BD%D0%B4%D0%B5%D0%BB%D1%8C%D1%88%D1%82%D0%B0%D0%BC,_%D0%9E%D1%81%D0%B8%D0%BF_%D0%AD%D0%BC%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'mandelshtamProfilePhoto.jpg'},
            'children': '',
            'parents': 'Эмилий Вениаминович Мандельштам (мастер перчаточного дела, купец 1-ой гильдии), Флора Овсеевна Вербловская (музыкант)',

          },
          {
            "name.last": "Анатолий",
            "name.first": "Мариенгоф",
            "patronymic": "Борисович",
            'birthDay': new Date(1897, 8, 6),
            'deathDay': new Date(1962, 7, 24),
            'birthCountry': 'Российская империя',
            'birthCity': 'Нижний Новгород',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%80%D0%B8%D0%B5%D0%BD%D0%B3%D0%BE%D1%84,_%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B9_%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'mariyengofProfiePhoto.jpg'},
            'children': 'Кирилл Анатольевич магиенгоф',
            'parents': 'Борис Михайлович Мариенгоф, Александра Николаевна Мариенгоф',

          },
          {
            "name.last": "Владимир",
            "name.first": "Маяковский",
            "patronymic": "Владимирович",
            'birthDay': new Date(1893, 8, 19),
            'deathDay': new Date(1930, 5, 14),
            'birthCountry': 'Российская империя',
            'birthCity': 'Багдати, Кутаисская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%8F%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'премия Ленинского комсомола, медаль "За усердие"',
            'additionalLinks': '',
            'authorPhoto': {filename: 'mayakovskiiProfilePhoto.jpg'},
            'children': 'Шлеб-Никита Антонович Лавинский, Патрисия Томпсон (Елена Владимировна Маяковская)',
            'parents': 'Владимир Константинович Маяковский (лесничий), Александра Алексеевна Павленко (казачка)',

          },
          {
            "name.last": "Дмитрий",
            "name.first": "Мережковский",
            "patronymic": "Сергеевич",
            'birthDay': new Date(1865, 9, 14),
            'deathDay': new Date(1941, 13, 9),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%80%D0%B5%D0%B6%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'merezhkovskyProfilePhoto.jpg'},
            'children': '',
            'parents': 'Сергей Иванович Мережковский (действительный статский советник), Варвара Васильевна Чеснокова (дочь обер-полицмейстера)',

          },
          {
            "name.last": "Вера",
            "name.first": "Меркурьева",
            "patronymic": "Александровна",
            'birthDay': new Date(1876, 10, 5),
            'deathDay': new Date(1943, 4, 20),
            'birthCountry': 'Российская империя',
            'birthCity': 'Владикавказ',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%80%D0%BA%D1%83%D1%80%D1%8C%D0%B5%D0%B2%D0%B0,_%D0%92%D0%B5%D1%80%D0%B0_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%BD%D0%B0',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'merkuryevaProfilePhoto.jpg'},
            'children': '',
            'parents': 'отец - землемер',

          },
          {
            "name.last": "Владимир",
            "name.first": "Набоков",
            "patronymic": "Владимирович",
            'birthDay': new Date(1899, 5, 22),
            'deathDay': new Date(1977, 8, 2),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B1%D0%BE%D0%BA%D0%BE%D0%B2,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': 'стипендия Гуггенхайма, номинация на Нобелевскую премию по литературе',
            'additionalLinks': '',
            'authorPhoto': {filename: 'nabokovProfilePhoto.jpg'},
            'children': 'Дмитрий Владимирович Набоков',
            'parents': 'Владимир Дмитриевич Набоков (юрист, политик, дворянин), Елена Ивановна Рукавишникова (дочь золотопромышленника)',

          },
          {
            "name.last": "Николай",
            "name.first": "Некрасов",
            "patronymic": "Алексеевич",
            'birthDay': new Date(1821, 13, 10),
            'deathDay': new Date(1877, 13, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Немиров, Подольская губерния',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BA%D1%80%D0%B0%D1%81%D0%BE%D0%B2,_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'nekrasovProfilePhoto.jpg'},
            'children': 'Иван Николаевич Некрасов',
            'parents': 'Алексей Сергеевич Некрасов (поручик, помещик, дворянин), Елена Андреевна Закревская (дочь посессионера)',

          },
          {
            "name.last": "Александр",
            "name.first": "Одоевский",
            "patronymic": "Иванович",
            'birthDay': new Date(1802, 13, 8),
            'deathDay': new Date(1839, 9, 27),
            'birthCountry': 'Российская империя',
            'birthCity': 'Санкт-Петербург',
            'wikipediaLink': 'https://ru.wikipedia.org/wiki/%D0%9E%D0%B4%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'odoevskiiProfilePhoto.JPG'},
            'children': '',
            'parents': 'Иван Сергеевич Одоевский (генерал-майор), Прасковья Александровна Одоевская (княжна)',

          },
          {
            "name.first": "Одоевский",
            "name.last": "Владимир",
            "patronymic": "Фёдорович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Островский",
            "name.last": "Александр",
            "patronymic": "Николаевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Парнок",
            "name.last": "София",
            "patronymic": "Яковлевна",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Пастернак",
            "name.last": "Борис",
            "patronymic": "Леонидовоч",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Платонов",
            "name.last": "Андрей",
            "patronymic": "",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Помяловский",
            "name.last": "Николай",
            "patronymic": "Герасимович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Прутков",
            "name.last": "Козьма",
            "patronymic": "Петрович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Радищев",
            "name.last": "Александр",
            "patronymic": "Николаевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Рылеев",
            "name.last": "Кондратий",
            "patronymic": "Фёдорович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Салтыков-Щедрин",
            "name.last": "Михаил",
            "patronymic ": "Евграфович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          }, {
            "name.first": "Северянин",
            "name.last": "Игорь",
            "patronymic": "",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Случевский",
            "name.last": "Константин",
            "patronymic": "Константинович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Сологуб",
            "name.last": "Фёдор",
            "patronymic": "Кузьмич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Станюкович",
            "name.last": "Константин",
            "patronymic": "Михайлович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Сумароков",
            "name.last": "Александр",
            "patronymic": "Петрович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Толстой",
            "name.last": "Алексей",
            "patronymic": "Константинович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Толстой",
            "name.last": "Лев",
            "patronymic": "Николаевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Тредиаковский",
            "name.last": "Василий",
            "patronymic": "Кириллович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Тургенев",
            "name.last": "Иван",
            "patronymic": "Сергеевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Тютчев",
            "name.last": "Фёдор",
            "patronymic": "Иванович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Успенский",
            "name.last": "Глеб",
            "patronymic": "Иванович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Фет",
            "name.last": "Афанасий",
            "patronymic": "Афанасьевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Херасков",
            "name.last": "Михаил",
            "patronymic": "Матвеевич",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Ходасевич",
            "name.last": "Владислав",
            "patronymic": "Фелицианович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Цветаева",
            "name.last": "Марина",
            "patronymic": "Ивановна",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Чарская",
            "name.last": "Лидия",
            "patronymic": "Алексеевна",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Чернышевский",
            "name.last": "Николай",
            "patronymic": "Гаврилович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Чуковский",
            "name.last": "Корней",
            "patronymic": "Иванович",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },
          {
            "name.first": "Чёрный",
            "name.last": "Саша",
            "patronymic": "",
            'birthDay': new Date(),
            'deathDay': new Date(),
            'birthCountry': 'Российская империя',
            'birthCity': '',
            'wikipediaLink': '',
            'honors': '',
            'additionalLinks': '',
            'authorPhoto': {filename: 'ProfilePhoto.jpg'},
            'children': '',
            'parents': '',

          },   
    ],


    Post: [
        {
            state: 'published',
            author: 'fedorAbramov',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'abramovResume.png'},
            __ref: 'post1',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'annaAchmatova',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'achmatovaResume.png'},
            __ref: 'post2',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'iosifBrodsky',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'brodskyResume.png'},
            __ref: 'post3',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'aleksandrPushkin',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'pushkinResume.png'},
            __ref: 'post4',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'michaelBulgakov',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'bulgakovResume.png'},
            __ref: 'post5',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'nikolaiGogol',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'gogolResume.png'},
            __ref: 'post6',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'sergeiEsenin',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'eseninResume.png'},
            __ref: 'post7',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'stanislavLem',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'lemResume.png'},
            __ref: 'post8',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'antonChehov',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'chehovResume.png'},
            __ref: 'post9',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'strugazkie',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'strugazkieResume.png'},
            __ref: 'post10',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'denisFonvizin',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'fonvizinResume.png'},
            __ref: 'post11',
            'likes': 0,
        },
        {
            state: 'published',
            author: 'velimirHlebnikov',
            publishedDate: new Date(2018, 5, 1),
            image: {filename: 'hlebnikovResume.png'},
            __ref: 'post12',
            'likes': 0,
        },
    ],


    PostComment: [
    ],


    PostLike: [
    ],
};